# Generated by Django 5.1.4 on 2025-02-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_teacher_slot_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
